project_id = "jmiigncmyirihxkuxybo"

[functions.send-booking-email]
verify_jwt = false

[functions.chat-bot]
verify_jwt = false

[functions.notify-agent-request]
verify_jwt = false

[functions.generate-tour-content]
verify_jwt = false

[functions.convert-image-webp]
verify_jwt = false
